### ISSUE TITLE
Update Geth to the latest version

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#107]
Right now the latest version is 1.8.3. We're still on 1.8.2 because there was a change in a Dockerfile that affects file permissions (geth no longer runs as `root`). The result is that the blockchain files on the persistent disk are no longer accessible to the user in the new image because they're still owned by root.

Fix it on the dev and staging clusters by manually changing permissions. It's fine to just clear the persistent disk if that's easier since these are not production clusters.

**Comment by cameel** [comment]
Actually the change will happen in 1.8.4 which has not been released yet. We encountered it because it's in the image tagged as `latest` on DockerHub. So this issue will only become relevant once 1.8.4 is released. I'm marking it as `locked` until then.

**Comment by cameel** [comment]
1.8.11 is out now. We should update. I'm removing the `locked` label.

**Comment by bartoszbetka** [comment]
It looks like in `v1.8.6` version the user changes are reverted.
