### ISSUE TITLE
'Metric XXX was not found in the cache' in Stackdriver logs

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#11]
Our logs on stackdriver contain lots instances of these three messages:

```
Metric stackdriver_sink_successfully_sent_entry_count was not found in the cache.
Metric stackdriver_sink_request_count was not found in the cache.
Metric stackdriver_sink_received_entry_count was not found in the cache.
```

We don't even have these metrics defined. Investigate why these messages show up and silence them by fixing the underlying problem.

**Comment by Gr33ny** [comment]
I think update the server-side kubectl version should solve our issue. 
Look out: 
https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/43 
and 
https://github.com/kubernetes/kubernetes/issues/54583

**Comment by bartoszbetka** [comment]
Problem solved by upgrading `concent-dev` cluster to newest version `1.8.5-gke.0
`.
