### ISSUE TITLE
Our SSL certificates do not have subjectAltName

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#138]
@jiivan Reports that the certificates we have generated for the testnet cluster (and likely for the other clusters too) produce the following warning:

```
SubjectAltNameWarning: Certificate for test.concent.golem.network has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
```

- Update the [command in our README](https://github.com/golemfactory/concent-deployment#generating-self-signed-certificates)
- Generate new certificates
- Post updated certificates on the wiki (https://github.com/golemfactory/concent-deployment-values/wiki/concent-status)
- Find out if there are any other issues we should know about. Post anything interesting you find in the comments below.

**Comment by bartoszbetka** [comment]
Some information about generating ssl certificate:
- https://gist.github.com/Soarez/9688998
- https://stackoverflow.com/a/27931596
- https://jamielinux.com/docs/openssl-certificate-authority/sign-server-and-client-certificates.html

Some information about best practices to use ssl:
- https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices
- https://sekurak.pl/kilka-slow-o-wdrozeniu-ssl-i-tls-cz-i/
- https://sekurak.pl/kilka-slow-o-wdrozeniu-ssl-i-tls-cz-ii/
- https://www.feistyduck.com/library/openssl-cookbook/online/apA-ssl-tls-deployment-best-practices.html
