### ISSUE TITLE
Make nginx-storage image usable for local development

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#141]
In #94 we prepared a script that runs a fake `nginx-storage`-like server in a docker container. This is fine for limited tests but we could actually go a step further and make it easy to run `nginx-storage` locally in a container. Currently all other components (Django server and workers, RabbitMQ, PostgreSQL) can be easily set up in development. nginx-storage is the only one (apart from the Django app) with non-trivial configuration but fortunately it does not depend on Kubernetes so running it locally seems entirely possible after a small refactoring.

1) **Move most of the static configuration from the config map to the container.**
    - Extract Lua code into a separate module with clearly defined functions
        - Remove all template variables (like `{{ upload_report_url }}`) from the function code. Replace them with ordinary Lua variables.
        - The module should load another small Lua module that will be provided by the config map and will contain values for the Lua variables that are meant to replace the template variables.
    - Move `error-pages.conf` to the container.
        - This will affect `nginx-proxy` too. The same source file should be used by both (don't duplicate it).
    - Move the content of the location blocks to a partial config file in the container. The config from the config map should now include this partial config from file instead of having it hard-coded.
        - The `server` block and most of the stuff that's directly in it (`listen` and `gzip_...` directives) should stay in the config map.
    - All the bits specific to Kubernetes should stay in the config map. The idea is for the container to contain all the reusable bits so that we can use them to write different overall configs for different environments but keep the same URLs and functionality.
2) **Create default nginx configuration in the container.**
    - Run it on port 8001.
    - It should be very simple, with no features like HTTPS or even gzip.
    - Assume that all the services it needs (like Conductor and Gatekeeper) are running on 127.0.0.1:8000.
    - It should include the config parts moved to the container.
    - If there's duplication between it and the config map, try to create more partial config files in the container.
3) **Test it in development.**
    - Test this with locally installed RabbitMQ, PostgreSQL, with the Django app running on `gunicorn` with all features enabled and with three local celery workers (one per queue).
        - Please ask @rwrzesien for help with that.
4) **Document steps needed to get the full setup for local development in concent-deployment README.**

The final structure we get should look like this:
- `containers/`
    - `nginx-proxy/`
        - `error-pages.conf`
    - `nginx-storage/`
        - `file-transfer-endpoints.conf`
            - Includes `file-transfer-endpoints.lua`
            - `location /download/`
            - `location /download-auth/`
            - `location = /upload/`
            - `location /upload-auth/`
            - `location @upload-internal`
            - `location /result/`
            - `location @upload-result`
        - `file-transfer-endpoints.lua`
            - Includes `file-transfer-config.lua`
            - `validate_upload_request()`
            - `validate_uploaded_file()`
            - `create_upload_location()`
            - `report_upload()`
            - `return_upload_success()`
        - `file-transfer-config.lua`
            - `upload_report_url` variable set to `http://127.0.0.1:8000`
        - `default.conf`
            - Defines the `server` block
                - No HTTPS and no redirect
                - No gzipping
                - Gatekeeper on `http://127.0.0.1:8000`
            - Includes `error-pages.conf` and `file-transfer-endpoints.conf`
- `kubernetes/config-maps/nginx-storage/`
    - `default.conf.j2`
        - `server` block with full HTTPS, gzipping and the rest of the current config
            - Includes `error-pages.conf` and `file-transfer-endpoints.conf`.
            - Includes `ssl.conf`.
    - `file-transfer-config.lua.j2`
        - `upload_report_url` variable set to a value from `var.yml`
    - `ssl.conf`

**Comment by dybi** [comment]
@cameel or @bartoszbetka , could you please update the description based on @bartoszbetka comment?

**Comment by cameel** [comment]
Updated.

I have also changed port for nginx-storage to 8001.
