### ISSUE TITLE
Virtual machine with services and dependencies for Concent

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#146]
Concent is accumulating more and more components. Setting them all up for local development is complicated and instructions depend on one's local environment (linux distribution, configuation, running servers in docker vs as daemons). To make it easier to get it all working we want to provide an example configuration running in a virtual machine. This machine can then serve as either an actual development environment or a reference for a developer who wants to set it up on his own.

This issue provides the first step to achieve this: a machine with all dependencies and services already installed and configured. After creating it the developer should be able to clone Concent repository and run it, as described in [Concent README](https://github.com/golemfactory/concent/blob/master/README.md).

1. Create a new Vagrant configuration in `concent-vm/`
    - You can use `concent-builder-vm/` as a base. Don't forget to give your machine a different local IP to allow both to run simultaneously.
    - Use a base image that has enough space for the blockchain.
    - The user should be able to specify `concent-deployment` version/branch via `CONCENT_DEPLOYMENT_VERSION` environment variable. If it's defined, pass the value to the playbook. Otherwise assume `master`.
2. Create an Ansible playbook for provisioning and make Vagrant run it. The playbook should:
    - Install RabbitMQ, PosgreSQL, Geth, Docker, git and Python (including virtualenv, pip and all the usual tools)
        - PostgreSQL, Geth and RabbitMQ, Docker should run as daemons.
        - Start them after installation.
        - Ensure that they start when the machine boots.
    - Create empty `control` and `storage` databases if they don't exist yet.
    - Configure geth to use testnet.
    - Install any system-level dependencies required by Concent, golem-messages and golem-smart-contract-interface (like OpenSSL or `libsecp256k1`, see [Concent README](https://github.com/golemfactory/concent/blob/master/README.md)).
    - Clone `concent-deployment` repository and create a working copy in the home directory.
        - Fetch the latest code if the repositoty already exists.
        - The branch/version should be passed in from the `Vagrantfile`.
    - Build `nginx-storage` Docker image.
    - Create a script that starts the latest version of `nginx-storage` container (see #141) and put it in `~/bin/`.
        - Consider creating a systemd service that starts the container (see [Creating Systemd Service Files](https://www.devdungeon.com/content/creating-systemd-service-files)) on system boot.
        - Run the container with `--network=host` so that it's available on `localhost`.
3. Make sure that the playbook works if you rerun it on an already created machine (with `vagrant provision`).
4. Update deployment README:
    - Say that it's possible to run such a local environment, list required programs (Vagrant, Ansible, etc.) and give the commands required to start and stop it.
    - Explain how to modify the `Vagrantfile` to share a directory with the host machine. Show how to use it to store Geth's blockchain on the host machine and avoid losing it and re-downloading it every time it's rebuilt.

**Comment by bartoszbetka** [comment]
We need also specify requirements for verification like: `blender`, `opencv`, `golem verification` etc. @cameel please, add some specification for this topic.

**Comment by bartoszbetka** [comment]
Change to use geth and rabbitmq as system libs #179

**Comment by cameel** [comment]
@bartoszbetka one important thing: please make sure that time synchronization is enabled in the machine. If not, enable it with `timedatectl`.

**Comment by cameel** [comment]
@bartoszbetka What about time synchronization? Have you checked/enabled it?
