### ISSUE TITLE
Helper scripts for managing a Concent instance in the virtual machine

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#148]
Create a set of helper scripts to automate typical activities necessary to manage a Concent instance.

Make the Ansible playbook for configuring the machine put them all in `~/bin/`. Also, make sure that this directory is in `PATH`.

1. `concent-env.sh`
    - Activates the virtualenv.
    - Changes directory to the root of the working copy (`~/concent/`).
    - This script is meant to be sourced rather than executed.
2. `concent-reset.sh`
    - Asks the user if he's sure (this is a destructive operation).
    - Destroys and recreates the databases.
    - Migrates the databases.
    - Empties RabbitMQ queues.
    - Re-creates the superuser account.
    - Restarts all the services (PostgreSQL, Geth, RabbitMQ, nginx-storage).
    - Should work even if the database and queues do not exist yet (so that it can be used to initialize the environment).
3. `concent-migrate.sh`
    - Migrates the databases.
4. `concent-update.sh [branch]`
    - Fetches the latest code from git
    - Tries to checkout the branch (fails if it can't)
        - Use `master` if the branch is not specified.
    - Destroys and recreates the virtualenv
    - Installs the requirements in the virtualenv
    - Migrates the databases
5. `concent-run.sh`
    - Starts `manage.py runserver`
    - Starts 3 `celery worker` instances, each one processing a different queue.
    - Processes should be started in such a way that they all print to the console and they're all killed when the script is killed. See [Run multiple commands and kill them as one in bash](https://unix.stackexchange.com/questions/204480/run-multiple-commands-and-kill-them-as-one-in-bash/430215#430215) for possible solutions - the one with a subshell looks simple and reilable.
    - Starts `nginx-storage` (unless you made a systemd service that manages it).

**Comment by bartoszbetka** [comment]
Replace `gunicorn` by `manage.py runserver`. The `gunicorn` need to setup proxy server to handle static content. We can simplify it by using `manage.py runserver` command which is load static files.

**Comment by cameel** [comment]
Updated. Looks like `manage.py runserver` is multithreaded after all. So it's fine.
