### ISSUE TITLE
Uploading files to nginx-storage without authentication

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#17]
Configure `nginx-storage` (#15) to allow uploading arbitrary files to its persistent disk. At this point accept anything, without worrying about permissions - this will be the subject of another task.

A POST request to `/upload/` with `multipart/form-data` content type and `Concent-Upload-Path` HTTP header should result in the included file being placed under the name specified in that header on the persistent disk. The name may be a relative path. The name specified in `Content-Disposition` of the multipart request should be ignored.

Allow uploading only one file at a time. A request with zero or more than one file should result in HTTP 400 error.

If possible, try to prevent overwriting existing files. If a file already exists, return a 4xx error. But if not create a separate task for this. It's something we'll have to deal with in a different way.

Ensure that if a download is interrupted, the partial file is not left under the target name (but it's OK to keep such files in temporary location and allow resuming uploads).

Enforce limits both on the size of individual files and on the total size of uploaded files. Limits should be configurable in [concent-deployment-values](https://github.com/golemfactory/concent-deployment-values).

### Example request
``` bash
curl -X POST http://storage.concent.golem.network/upload/ \
    --header "Concent-Upload-Path: blender/benchmark/test_task/scene-Helicopter-27-cycles.blend" \
    --form file=@scene-Helicopter-27-cycles.blend
```

**Comment by cameel** [comment]
Task description updated:
- Accept exactly one file
- The header with file name should be called `Concent-File-Path`. Ignore the name specified in the multipart request because it cannot contain a path.
- If not possible to prevent overwriting files, give up. We'll deal with it in a different way, later.

**Comment by cameel** [comment]
More updates:
- The header with the file name should be called `Concent-Upload-Path`, not `Concent-File-Path`.
- Added an example curl call.

**Comment by bartoszbetka** [comment]
Some part of task wasn't made and can be potential problem in future: 
- Sending multiple files in one request saves all files to one large file.
- File with the same name are overwriting.

The limitations that have occured:
- Content-type `multipart/formdata` is not supported by nginx-big-upload module. Instead, we can use only `application/x-www-form-urlencoded`.
-  Content of  `Concent-Upload-Path` header is checked only on gatekeeper application.

Example request for upload:
```
curl -X POST http://storage.concent.golem.network/upload/ \
    --header "Concent-Upload-Path: blender/benchmark/test_task/scene-Helicopter-27-cycles.blend" \
    --data-binary "@scene-Helicopter-27-cycles.blend"
```
