### ISSUE TITLE
Signing Service container

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#185]
This is a part of the implementation of the "Concent Signing Service" blueprint (https://github.com/golemfactory/concent/issues/597).

#### Overview
We need to have a separate container for the Signing Service. It should be able to run both on Kubernetes and without it. We want to be able to set it up ourselves on test clusters but in production it will be running on Golem's infrastructure.

In addition to building the container our build system should also be able to generate a self-contained package that allows anyone to build the service.

#### Building the container
The container should be based on Debian or Alpine Linux.

1. Dependencies
    - Install system dependencies.
    - Install Python dependencies from `concent/signing_service/requirements.lock`.
        - This is not a Django project so it does not require anything extra to serve it (gunicorn, celery, etc.).
2. Signing Service
    - Install source from `concent/signing_service/` in the container.
        - It's very likely that the service will require some files from the other directories. We'll know for sure when the service is implemented. Be prepared to update the container if that turns out to be the case.
    - Include a file with version
        - Signing Service uses has the same version as Concent.
    - When building, put the source of the service in a subdirectory of the directory that contains the `Dockerfile`. The directory should contain everything that's needed to build it.
3. Runner
    - Create a simple runner script that will execute the script from `concent/signing_service/` and pass all command-line parameters to it. Put it in `/usr/local/bin` so that we don't have to use the full path to run it.
    - Include an entry point that runs the script as non-root user.
    - The container should run the runner script by default when it starts .

#### Source package
Add a step in `containers/Makefile` that creates `concent-signing-service-<version>.tar.xz` archive that contains:
- Dockerfile (after template rendering) and all the scripts it installs in the machine
- The source of the Signing Service
- Version file

Create a phony target called `concent-signing-service-package` that can be used to build it without specifying the version on the command line.

It should be possible to build the container simply by unpacking the package and running `docker build` inside.

#### Instructions
In README include instructions for both building the package and manually building the container by extracting the package. Include a link to the `Dockerfile` in the repository so that someone reading the docs can easily take a look at it.

Also show how to run the container and how to attach a volume with Ethereum public key and pass the full path to that file on the command line.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159031618
