### ISSUE TITLE
External access to Middleman

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#188]
This is a part of the implementation of the "Concent Signing Service" blueprint (https://github.com/golemfactory/concent/issues/597). It depends on #187.

Configure `nginx-proxy` to proxy TCP traffic on port 9055 to the `middleman` container.

See [NGINX Load Balancing – TCP and UDP Load Balancer](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/).

You'll need nginx with the [stream module](https://nginx.org/en/docs/stream/ngx_stream_core_module.html). If it's hard to install it in our `nginx-proxy` container, consider switching the container to OpenResty, which seems to provide it out of the box.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159099416
