### ISSUE TITLE
Make nginx-storage use gatekeeper app for permission checks on file transfers

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#19]
Configure `nginx-storage` to use [ngx_http_auth_request_module](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) to pass upload and download requests to our [gatekeeper app](https://github.com/golemfactory/concent/issues/6).

Download requests have the path embedded in the URL. Remove the `/download/` prefix and send a the authorization request to `http://gatekeeper-container/gatekeeper/download-auth/<path>`.

Upload requests have the path in a header called `Concent-Upload-Path`. While sending the authorization request, remove the header and append path to the authorization URL: `http://gatekeeper-container/gatekeeper/download-auth/<path>`

### Error handling
Also, configure it to respond with JSON (rather than the default HTML) if access is denied. By default a negative response looks like this:

``` html
<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.13.7</center>
</body>
</html>
```

We prefer this:

``` json
{
    "error_message": "Authorization required. You must use a token to access the requested files.",
    "error_code":    "authorization-required"
}
```

Don't forget about the proper `Content-Type` (`application/json`) for JSON responses.

#### Download request
``` bash
curl http://storage.concent.golem.network/download/blender/benchmark/test_task/scene-Helicopter-27-cycles.blend \
    --header "Authorization: Golem dG9rZW4K" \
    --header "Concent-Client-Public-Key: MTIzNDU2Cg=="
```

The URLs that should be used with `auth_request`: `http://gatekeeper-container/gatekeeper/download-auth/blender/benchmark/test_task/scene-Helicopter-27-cycles.blend`.

#### Upload request
The request that goes to `nginx-storage`:
``` bash
curl -X POST http://storage.concent.golem.network/upload/ \
    --header "Authorization: Golem dG9rZW4K" \
    --header "Concent-Client-Public-Key: MTIzNDU2Cg==" \
    --header "Concent-Upload-Path: blender/benchmark/test_task/scene-Helicopter-27-cycles.blend" \
    --form file=@scene-Helicopter-27-cycles.blend
```

The URLs that should be used with `auth_request`: `http://gatekeeper-container/gatekeeper/upload-auth/blender/benchmark/test_task/scene-Helicopter-27-cycles.blend`.

**Comment by cameel** [comment]
Here's an example of using `ngx_http_auth_request_module`.

Place this file in `/tmp/http/default.conf`:
``` nginx
log_format custom_log_format
    'Referer:       $http_referer\n'
    'User Agent:    $http_user_agent\n'
    'Authorization: $http_authorization\n'
    'Request body:  $request_body';

access_log /dev/stdout custom_log_format;

server {
    listen  80;
    charset utf-8;

    location = /private/ {
        auth_request     /auth/;
        auth_request_set $auth_status $upstream_status;

        proxy_pass       http://localhost/secret/;
    }

    location = /auth/ {
        internal;
        proxy_pass              http://localhost/allow/;
        #proxy_pass              http://localhost/deny/;
        proxy_pass_request_body off;
        proxy_set_header        Content-Length "";
        proxy_set_header        X-Original-URI $request_uri;
    }

    location = /allow/ {
        return 200 "Access granted!";
    }

    location = /deny/ {
        return 401 "Access denied!";
    }

    location = /secret/ {
        return 200 "<insert a secret message here>";
    }
}
```

Run a docker container with nginx using this configuration:
``` bash
docker run \
    --rm \
    --volume /tmp/http/default.conf:/etc/nginx/conf.d/default.conf:ro \
    --name nginx \
    nginx:alpine
```

Now you can test it with:
``` bash
container_ip=$(docker inspect nginx --format '{{.NetworkSettings.Networks.bridge.IPAddress}}')

curl -X POST $container_ip/private/ \
    --header "Authorization: Golem ABCDEFGHIJ"
```

This configuration creates a `/private/` endpoint that redirects to `/secret/` on the same nginx instance (but be configured to do anything: serve a static page, pass the request to another server, etc.). Before the request is processed, nginx calls `/auth/` which is configured to ask another server for permission. In this case this other server is the same nginx instance, but it could just as well be another service available on the network.

The server is configured to log details of all incoming requests so you can see exactly what's happening and in what order.

You can replace `/allow/` with `/deny/` to see the effects of a denied request.

**Comment by cameel** [comment]
Also, some examples of complete nginx configurations with this module:
- [Authentication Based on Subrequest Result](https://www.nginx.com/resources/admin-guide/restricting-access-auth-request/)
- [Example NGINX configuration using auth_request and auth_request_set directives to route users ](https://gist.github.com/kmjones1979/3c6ae6645c6814084a655d73f59f47e9)

**Comment by cameel** [comment]
I have updated the task description:
- Added example curl commands that should work with the server
- Defined expected gatekeeper URLs
- Changed how the path is passed to gatekeeper in case of upload. Formerly gatekeeper was meant to get the `Concent-File-Path` header and process it by itself. Now nginx should just append it to the path and remove the header.
    - I think that we'll eventually remove the header on the nginx side too but for now I'm leaving it not to complicate the upload implementation.

**Comment by cameel** [comment]
One more update: the header with the file name should be called `Concent-Upload-Path`, not `Concent-File-Path`.

**Comment by Gr33ny** [comment]
I found this solution a few days ago, 
@cameel & @bartoszbetka look out: 
https://stackoverflow.com/questions/37523615/dynamic-proxy-pass-in-nginx-to-another-pod-in-kubernetes
