### ISSUE TITLE
Kubernetes deployment for Signing Service

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#192]
This is a part of the implementation of the "Concent Signing Service" blueprint (https://github.com/golemfactory/concent/issues/597). It depends on #185.

#### Overview
In production the Signing Service will be running on Golem's infrastructure but on the test clusters we need to run it ourselves. The goal of this issue is to add a Kubernetes deployment for the service and a deployment option that enables it on the cluster.

#### Deployment
Create `signing-service` deployment:
- Use `concent-signing-service` image as a base.
- Run the main script that starts the service.
- Attach secrets in a volume
    - A file with ethereum private key
- It does not need a Kubernetes service. It won't be accepting connections from other containers.
- The number of replicas should be hard-coded to 1. At any given time there can be at most one instance.
- Define resource limits for the image. They can be low since the service is pretty light on dependencies.

#### Running Signing service
Run the main script with the following parameters:
- Host: external address of the control cluster
- Port: external port of the middleman container (9055)
- Sentry DSN: same value we use in Django

#### Deployment configuration
- The service should be deployed only on the `dev` and `staging` clusters.
- Remove `ETHEREUM_PRIVATE_KEY` setting from `local_settings.py` of all existing containers.

#### Virtual machine
Add Signing Service to our virtual machine (#147, #148). If that task is not merged before this one, make modifications in its pull request and rebase on changes made here.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159170211
