### ISSUE TITLE
Allow specifying a custom location to deployment configuration in Kubernetes Makefile

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#195]
Currently [kubernetes/Makefile](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/kubernetes/Makefile) assumes that `var.yml` and other configuration files from [concent-deployment-values](https://github.com/golemfactory/concent-deployment-values) repository are copied or linked to the `kubernetes/` subdirectory. It would be more convenient if we could just tell make where those files are located.

We want to be able to run make like this:

``` bash
cd kubernetes/
make DEPLOYMENT_VALUES_DIR=../../concent-deployment-values <other make options>
```

To achieve this, modify the `Makefile`:
- Add a variable called `DEPLOYMENT_VALUES_DIR`
- Use the current directory by default
- Use the variable everywhere where `var*.yml` files are used inside the `Makefile`.

When this is done also adjust our docs and playbooks to use the new method:
- In README remove the information that you have to create symbolic links to these files
- In [build-test-and-push.yml](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/concent-builder/build-test-and-push.yml) when running `kubernetes/Makefile`, either don't use the variable and rely on the default value or use it with the path to the `Makeile` directory. The playbook is already uploading the files to that directory.

Finally, make sure that you can successfully run the playbooks to build and deploy Concent without the symbolic links.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159197826

**Comment by cameel** [comment]
Update. Playbook should run `make` without the new variable.
