### ISSUE TITLE
Separate cloud management from cluster deployment

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#198]
#### Overview
Concent stores its data on a [PostgreSQL database server managed by Cloud SQL](https://cloud.google.com/sql/docs/postgres/). Creation and removal of a database is a part of a cluster deployment process.

PostgreSQL has an extensive [privilege system](https://www.postgresql.org/docs/current/static/sql-grant.html) but there's no way to grant permissions to a specific database while it does not exist. This means that to create a database during deployment one needs to be able to create or delete arbitrary databases, also those belonging to other clusters. Currently we grant this privilege only to the database administrator (`postgres` role) which means that even someone deploying to the `dev` cluster needs to know superuser credentials.

The goal of this task is to separate database management from cluster deployment. All databases should be created ahead of time by someone with access to all the clusters. Cluster deployment process should be altered so that it clears an existing database and reuses it instead of dropping it and recreating it. This will make it possible to allow someone to deploy a single cluster without letting him access databases belonging to other clusters.

Managing databases is only one example of activities that I refer to as "cloud management". These include also creating/deleting persistent disks, creating/deleting clusters, reserving IPs. Basically, anything that requires access to the whole Google Cloud project rather than just to a specific Kubernetes cluster within that project. All of those things will later be scripted but right now we do them manually - that's why in this issue we focus solely on the database management.

#### Secrets
We want to separate cluster-level secrets from cloud-level secrets. Currently the cluster deployment scripts assume that there's one secret directory per cluster and it contains a file called `var-secret.yml` with the following fields:
- `db_admin_password`
- `db_user_password`
- `django_admin_password_hash`
- `rabbitmq_password`

From now on we want to have a separate directory for cloud-level secrets. This directory should have a file called `cloud-secrets.yml` and `db_admin_password` should be moved to that file. `var-secret.yml` should be renamed to `cluster-secrets.yml` and contain all the other fields.

Eventually build server will contain only `cluster-secrets.yml` for every test cluster (`dev`, `staging`, `testnet`). `cloud-secrets.yml` together with `cluster-secrets.yml` for `mainnet` cluster will only be available on a special machine used only for deployment.

**Do not** upload `cloud-secrets.yml` to the build server in `install-repositories.yml` playbook. Only the `cluster-secrets.yml` will now be needed for cluster deployment.

#### Cloud management playbooks
1. Create a directory called `cloud/` in the root directory of the repository. The directory will contain all the cloud management scripts and playbooks.
2. Create the following playbooks inside the new directory:
    - `create-databases.yml`: creates all databases and roles listed in the cluster configuration (`var-xxx.yml`).
    - `drop-databases.yml`: drops all databases and roles listed in the cluster configuration (`var-xxx.yml`).
    - If possible, reuse code from existing playbooks for `concent-builder`.

These playbooks will eventually be executed against a special deployment machine but for now assume that they're running on the build server. You may need to add the build server to the Cloud SQL IP whitelist  for now.

#### Modify cluster deployment
1. Replace the [create-database.sh](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/containers/postgresql/create-database.sh) and [delete-database.sh](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/containers/postgresql/delete-database.sh) scripts in the `postgresql` container with one called `reset-database.sh`.
    - The script should clear an existing database by dropping all [schema](https://www.postgresql.org/docs/10/static/ddl-schemas.html)s and creating an empty schema called `public` (the default schema in PostgreSQL).
2. Replace the [create-database](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/kubernetes/jobs/create-database.yml.j2) and [delete-database](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/kubernetes/jobs/delete-database.yml.j2) jobs with one called `reset-database`. It should use `reset-database.sh` to clear an existing database.
3. Remove `db_admin_password` from [db-secrets](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/kubernetes/secrets/db-secrets.yml.j2) secret and modify the jobs to use `db_user_password` (and the user role) instead.
4. Merge [create-job-dependencies.sh](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/kubernetes/create-job-dependencies.sh) and [delete-job-dependencies.sh](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/kubernetes/delete-job-dependencies.sh) with [create-config-maps.sh](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/kubernetes/create-config-maps.sh.j2) and [delete-config-maps.sh](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/kubernetes/delete-config-maps.sh). We no longer need to be able to create and delete them separately. The secrets used by jobs no longer contain the admin key for the database and can stay on the cluster.

#### Modify deployment playbooks
In this issue we assume that cluster management is still done from the build server. Eventually we want to have a separate machine just for storing the production secrets and deployment but this is out of scope of this particular issue.

1. Replace [create-db.yml](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/concent-builder/create-db.yml) and [delete-db.yml](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/concent-builder/delete-db.yml) with `reset-db.yml`.
2. Update deployment instructions in `README`.
    - Say that creating the databases is a separate step and requires access to the whole Google Cloud project. Normal cluster deployment only involves a reset or a migration.

#### `create-databases.yml` playbook
Parameters:
- `cluster`: name of the cluster, e.g. `concent-dev`.

The playbook should load the YAML files containing both cloud and cluster secrets.

Behavior:
- Use PostgreSQL client to create the database and role for the control cluster using values from `control_database_yyy` variables in `var-xxx.yml` and passwords from cluster and cloud secrets.
- Do the same for the storage database.
    - Create a helper playbook or a role that can be imported to avoid duplicated code.

##### Helper role
This should work in a similar way to how [create-database.sh](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/containers/postgresql/create-database.sh) works now but the privileges should be a little different.

Parameters:
- Database host: IP of our Cloud SQL instance
- Database name
- Role name
- Role password
- Admin password

Passwords should never be passed directly to shell commands. Pass them via shell variables or files.

Behavior
1. Create database if it does not exist yet.
2. Create role if it does not exist yet.
    - Should own the new database and everything inside
    - Should **not** be able to create or drop databases (including its own database)
    - Should be able to create and destroy schemas inside its own database.

See [GRANT](https://www.postgresql.org/docs/current/static/sql-grant.html) for information about adding and revoking privileges.

#### `drop-databases.yml` playbook
Parameters:
- `cluster`: name of the cluster, e.g. `concent-dev`.

The playbook should load the YAML files containing both cloud and cluster secrets.

Behavior:
- Use PostgreSQL client to drop the database and role for the control cluster using values from `control_database_yyy`.
- Do the same for the storage database.
    - Create a helper playbook or a role that can be imported to avoid duplicated code.

##### Helper role
This should work in a similar way to how [delete-database.sh](https://github.com/golemfactory/concent-deployment/blob/v0.7.3/containers/postgresql/delete-database.sh) works now.

Parameters:
- Database host: IP of our Cloud SQL instance
- Database name
- Role name
- Admin password

Behavior
1. Drop the database if it exists.
2. Delete the role if it exists.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159326102

**Comment by bartoszbetka** [comment]
This variable is not used: `rabbitmq_password`.

**Comment by cameel** [comment]
So why is it still there? Remove it then :)

**Comment by bartoszbetka** [comment]
This [solution](https://github.com/golemfactory/concent-deployment/pull/226#discussion_r222375134) should be considerated in different pull request. We use the `create-job-dependencies.sh` script also in the `reset-database.yml` playbook which is require delete services from cluster before running. We use for this the `delete-service.sh` script which is also delete all configmaps.
