### ISSUE TITLE
Separate build step for secrets

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#203]
#### Overview
Currently `kubernetes/Makefile` builds all Kubernetes manifests, including secrets. The secrets are then bundled along with all the other files. We'll be switching to Helm/Tiller soon and if we converted it as it is now, the secrets would be a part of the helm chart (i.e. the deployment package). This would make it necessary to protect those charts themselves.

We want to change it so that one can build Kubernetes manifests without access to secrets and treat deployment packages like any other build artifact. Secrets should be in a separate package and only this package should need protection.

### Secret builder
- Create a directory called `secrets/` in the root of the repository
- Create a `Makefile` in it:
    - Parameters/variables:
        - `CONCENT_SECRET_DIR`
    - Targets:
        - Kubernetes manifests (i.e. the .yml files) for all secrets used on the cluster
            - Use the commands from [kubernetes/create-config-maps.sh](https://github.com/golemfactory/concent-deployment/blob/v0.8.0/kubernetes/create-config-maps.sh.j2) and simply add `--dry-run` to `kubectl create secret` to get the .yml files.
        - The other usual stuff like `clean`, `all`, etc. See our other Makefiles.
- Create a script called `apply-secrets.sh`
    - The script should create all secrets on the cluster using `kubectl apply`.
- Create a script called `delete-secrets.sh`
    - The script should remove all secrets from the cluster using `kubectl delete`.

### Remove secrets from `kubernetes/`
- Remove all calls related to secrets from [create-config-maps.sh](https://github.com/golemfactory/concent-deployment/blob/v0.8.0/kubernetes/create-config-maps.sh.j2), [create-job-dependencies.sh](https://github.com/golemfactory/concent-deployment/blob/v0.8.0/kubernetes/create-job-dependencies.sh), [delete-config-maps.sh](https://github.com/golemfactory/concent-deployment/blob/v0.8.0/kubernetes/delete-config-maps.sh) and [delete-job-dependencies.sh](https://github.com/golemfactory/concent-deployment/blob/v0.8.0/kubernetes/delete-job-dependencies.sh). They should now assume that the secrets always exist on the cluster.
- Move everything from [kubernetes/secrets/](https://github.com/golemfactory/concent-deployment/tree/v0.8.0/kubernetes/secrets) directory directly to our new `secrets/` directory.
- Stop creating intermediate files containing secrets in `kubernetes/Makefile`:
    - `%-db-secrets.yml` should be moved to the secret builder.
    - `%-database-configuration.yml` contains some configuration in addition to secrets (e.g. login, host name, `initialize_django_admin`). You can leave it if it's still needed after you remove secrets from it.
    - `vars-merged-with-secrets.yml` and `vars-with-%-database-config-and-secrets.yml` are no longer needed.
- Remove `CONCENT_SECRET_DIR` from `kubernetes/Makefile`. 
- Remove the `concent-secrets/%` rule.

### Update playbooks
1. [build-test-and-push.yml](https://github.com/golemfactory/concent-deployment/blob/v0.8.0/concent-builder/build-test-and-push.yml):
    - Add a new step that builds the secrets
    - Don't pass `CONCENT_SECRET_DIR` to `kubernetes/Makefile`.
    - Don't pass `CONCENT_SECRET_DIR` to `containers/Makefile` (this makefile does not even support this variable - it should have never been there). 
2. [deploy.yml](https://github.com/golemfactory/concent-deployment/blob/v0.8.0/concent-builder/deploy.yml):
    - Run `apply-secrets.sh` after destroying and before recreating services on the cluster.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159497259

**Comment by bartoszbetka** [comment]
@cameel I think you want use here `apply-secrets.sh`.
> Run deploy-secrets.sh after destroying and before recreating services on the cluster.

**Comment by cameel** [comment]
Thanks. Fixed.

**Comment by cameel** [comment]
Update: Removed the `templates/` subdirectory. Templates should be moved directly to `secrets/`.
