### ISSUE TITLE
Separate secret deployment from cluster deployment

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#204]
This task depends on #203.

### Overview
Currently we destroy and recreate secrets as a part of the cluster deployment process. This means that you need to be able to access the secrets to put a new version on the cluster.

We'd like to change that so that secrets are uploaded to the cluster once and then every subsequent deployment uses these secrets. Secrets will now change only we want to actually change passwords or certificates, not all the time.

This is a step towards encrypting secrets at rest. Such encryption will require using a password or a key every time secrets are deployed so deploying them with every change to the code would quickly become a burden, especially on the dev clusters. We could treat dev differently but we don't really have to if we introduce the mechanism described here.

### Playbooks
In addition to the stuff below, remove `var-secrets.yml` from any playbooks that don't really need them.

#### `cluster-deploy-secrets.yml`
This is a new playbook. It's meant to be run when secrets need to be uploaded to a clean cluster or updated on an existing cluster.

Steps:
- Builds secrets using `secrets/Makefile`.
- Deploys secrets to a cluster using `secrets/apply-secrets.sh`.
- Cleans the `build/` directory so that unencrypted secrets are not left laying around.
    - This should be done even if the operation fails.

#### `cluster-remove-secrets.yml`
This is a new playbook. It's meant to be run when we want to completely remove secrets from the cluster. It's only needed when we want to stop using the application on a given cluster or when new secrets no longer contain some files and we don't want to leave them on the cluster. To simply update older secrets use `deploy-secrets.yml` instead.

Steps:
- Deletes all secrets from the `default` namespace on the cluster.
    - **All** secrets - not only the ones created by `apply-secrets.sh`.

#### `build-test-and-push.yml`
- Remove the step that builds secrets.

#### `deploy.sh`
- Remove the step that deploys the secrets to the cluster.

#### `install-repositories.yml`
No changes here (yet). This playbook is still responsible for uploading secrets to the cluster. All other playbooks should assume that the secrets are already on the server.

### README
Update deployment instructions in the README. Deploying/deleting secrets and creating/deleting a database (#198) should now be in a separate section called "Cloud Management", separate from the one that describes cluster deployment.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159497324
