### ISSUE TITLE
Consolidate secrets

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#205]
This task depends on #198.

### Overview
In #198 there were some initial changes in how we store secrets but that was just enough to make it possible to do that task. In this one we want to clean up the structure a bit to consolidate the files and remove duplication.

### Changes
- Merge `secrets.py` and `cloud-secrets.yml`.
    - `DATABASE_PASSWORD` is the same thing as `db_user_password` (except that `db_user_password` is base64 encoded).
    - `secrets.py` should now be generated by the `Makefile` from secrets and a template.
- Move `concent-builder-service-private-key.json`.

#### Structure after #198
`concent-secrets/`
- `cloud/`
    - `cloud-secrets.yml` with the following variables:
        - `db_admin_password`
- `concent-dev/`
    - `secrets.py` with the following variables:
        - `SECRET_KEY`
        - `DATABASE_PASSWORD`
        - `EMAIL_PASSWORD`
        - `CONCENT_PUBLIC_KEY`
        - `CONCENT_PRIVATE_KEY`
        - `SENTRY_DATA_SOURCE_NAME`
    - `cluster-secrets.yml` with the following variables:
        - `db_user_password`
        - `django_admin_password_hash`
        - `rabbitmq_password`
    - `concent-builder-service-private-key.json`
    - `nginx-proxy-ssl.crt`
    - `nginx-proxy-ssl.key`
    - `nginx-proxy-storage.crt`
    - `nginx-proxy-storage.key`
- `concent-staging`: structure the same same as in `concent-dev/`
- `concent-testnet`: structure the same same as in `concent-dev/`
- `concent-mainnet`: structure the same same as in `concent-dev/`

#### Structure we want
`concent-secrets/`
- `cloud/`
    - `cloud-secrets.yml` with the following variables:
        - `database_admin_password`
    - `concent-builder-service-private-key.json`
- `concent-dev/`
    - `cluster-secrets.yml` with the following variables:
        - `django_secret_key`
        - `concent_public_key`
        - `concent_private_key`
        - `django_admin_password_hash`
        - `database_user_password`
        - `rabbitmq_password`
        - `email_password`
        - `sentry_data_source_name`
    - `nginx-proxy-ssl.crt`
    - `nginx-proxy-ssl.key`
    - `nginx-proxy-storage.crt`
    - `nginx-proxy-storage.key`
- `concent-staging`: structure the same same as in `concent-dev/`
- `concent-testnet`: structure the same same as in `concent-dev/`
- `concent-mainnet`: structure the same same as in `concent-dev/`

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/159522588

**Comment by bartoszbetka** [comment]
Update: 
- We don't use `rabbitmq_password` variable -deleted
- We use two separate `django_secret_key` for different database, modify to: `django_control_secret_key` and `django_storage_secret_key`

**Comment by cameel** [comment]
> - We use two separate `django_secret_key` for different databases, modify to: `django_control_secret_key` and `django_storage_secret_key`

It does not really matter. This could just as well be a single key. It's only important that it's random and remains a secret.
