### ISSUE TITLE
Encrypting secrets at rest with Ansible Vault

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#206]
This task depends on #204 and #205.

### Overview
There are four types of places where we store secrets:
1. On the machines of people who run Ansible playbooks to provision the build server.
2. On the build server in a global directory.
3. On the build server in a local build directory (briefly, when Kubernetes secret manifests are built).
4. On the cluster.

In all of these places secrets are currently unencrypted. Ultimately they must end up unencrypted on the cluster for the application to be able to access them but we could secure them in the other locations to decrease the chances of them leaking.

The goal of this task is to use [Ansible Vault](https://docs.ansible.com/ansible/latest/user_guide/vault.html) to encrypt our secrets in locations 1. and 2. and decrypt them just before the Kubernetes secret manifests are built.

### Secret encryption
#205 shows how our secrets are structured now. They should still have that structure when decrypted.

When encrypted, the directories should stay the same, but each file should get an additional `.vault` extension. E.g. `concent-secrets/concent-dev/cluster-secrets.yml` should become `concent-secrets/concent-dev/cluster-secrets.yml.vault` when encrypted.

#### Vault passwords
Vault password is the same for all encrypted files within one "secret set" (e.g. all secrets for `concent-dev` or `cluster`). But different sets may have different passwords. Currently we need three passwords:
1. One for `concent-dev`, `concent-storage` and `concent-testnet`. These are not very sensitive and the password can be weak and convenient.
2. One for `concent-mainnet`. This is highly sensitive and needs a strong password.
3. One for `cluster`. This one gives access to the whole cloud infrastructure and should have a strong password too. With access to the infrastructure it's easy to intercept mainnet secrets in an unencrypted form.

The passwords should be decided ahead of time and shared between all the people who have permission to manage the cloud infrastructure. People that only deploy the application to a single cluster **do not** need to know these passwords. They can expect that the secrets they need are either already on the cluster (if needed by the application) or on the build server (if needed for deployment). 

Each person with access to the password is responsible for securing it by either memorizing it and never writing it down or using a password manager.

### Uploading and decrypting secrets
Secrets should never be stored outside of the deployment server or the cluster in an unencrypted form. 

Upload and decryption should be performed by the `cluster-deploy-secrets.yml` playbook using Ansible's `copy` module. The playbook should ask user for passwords to them (Ansible can do that automatically). Then it should decrypt the secrets and put them in in the build directory. In that form they can be used by `secrets/Makefile`.

Secrets (and all files that contain them) must always be removed after the build and deployment, no matter whether the operation is successful or not.

### Clean up unencrypted secrets
After you implement this, make sure that there are no unencrypted secrets left on the build server. Tell other people to delete them from their machines too.

Then change the master password to Cloud SQL.

We don't have `mainnet` secrets yet and those on the other clusters are not sensitive so changing them is not necessary. Still, it might be a good idea to change `testnet` passwords.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159523237

**Comment by bartoszbetka** [comment]
There is a problem with second point `2. On the build server in a global directory.`. I consider to not store on build server encrypted secrets. Ansible allow decrypting with copy module but only from local machine to remote machine. I think that we should copy decrypted secrets from local machine only when we want do deploy they in cluster or activate service account that allow connection to cluster by kubectl and then delete they. However, if we want still keep encrypted secrets on remote machine i try apply some workaround.
https://github.com/ansible/ansible/issues/41130

**Comment by cameel** [comment]
OK. In that case let's drop the part about storing the secrets on the server. Let's assume they're present on the machine you're running Ansible from.

**Comment by cameel** [comment]
Description updated/
