### ISSUE TITLE
Blocking HTTP access to nginx-storage would prevent verifier from downloading files over HTTP

### ISSUE THREAD

**Issue by michalpiasecki1** [golemfactory/concent-deployment#213]
Variable `nginx_storage_allow_http` from `kubernetes/config-maps/nginx-storage/default.conf.j2` may disable allow http even from inside the cluster. HTTP traffic incoming from cluster should always be permitted.

**Comment by bartoszbetka** [comment]
I don't see a problem, what about this part of code https://github.com/golemfactory/concent-deployment/blob/master/kubernetes/config-maps/nginx-storage/default.conf.j2#L26-L30. I analyzed the problem to make sure that error not occurred and all works.
