### ISSUE TITLE
Disable HTTP on the staging cluster

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#214]
All our clusters allow access over HTTPS. Some are also configured to allow plain HTTP traffic. These are currently `dev` and `staging`. We want to disable HTTP on `staging` so that its configuration is closer to `testnet`.

Make sure **not** to disable it for `nginx_storage` - currently that's an internal connection and needs HTTP. Only disable it for `nginx_proxy`.

After changing this, deploy the latest code to the `staging` cluster.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/159850094

**Comment by michalpiasecki1** [comment]
http on staging nginx_proxy disabled.
