### ISSUE TITLE
Configure CONCENT_FEATURES in local_settings

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#22]
Add `CONCENT_FEATURES` setting to `local_settings.py` in the config map. Currently it's not configured and the application sends crash reports like this one on any access attempt:

```
Exception Type: AssertionError at /admin/ Exception Value: CONCENT_FEATURES variable must be defined in django settings. Request information: USER: AnonymousUser
```

**Comment by Jakub89** [comment]
I've made two pull requests to solve the issue. One here and other in concent-deployment-values. I haven't tested it yet, I would need help from one of guys working on deployment.

**Comment by cameel** [comment]
@bartoszbetka Could you deploy this and check if it works?

**Comment by cameel** [comment]
Merged into master.
