### ISSUE TITLE
Passing environment name to the Signing Service

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#221]
When https://github.com/golemfactory/concent/issues/762 is implemented, add `--sentry-environment` option to the command line of the Signing Service when started on the cluster.

Don't forget to update the `README`.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160650786

**Comment by pawelkisielewicz** [comment]
It is done in https://github.com/golemfactory/concent/pull/768
