### ISSUE TITLE
Stop using Python 2 on concent-builder

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#227]
Looks like both Ansible and yasha now support Python 3:
- [Ansible > Python 3 Support](https://docs.ansible.com/ansible/2.6/reference_appendices/python_3_support.html)
- [yasha README](https://github.com/kblomqvist/yasha/blob/master/README.md)

So we finally stop using Python 2 on our machines.

Update concent-builder playbooks so that Python 2 is no longer installed or used for anything.

If we're using Python 2 anywhere else in our deployment, leave a comment below and get rid of it too.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/160311023

**Comment by bartoszbetka** [comment]
The`ansible` needs a `python2` or `python3` on the target machine. It's modules are based on python, so I see three solution from this problem:
- change our `configure.yml` playbook to use shell comand with `raw` module before install `python3`
- assume that `python2` will be added to the system installation and not delete it
- manually install `python3` on the server and then run playbooks.

**Comment by cameel** [comment]
Our playbooks don't need to be that universal. We only run them on servers and virtual machines where we know what the system image is so we know whether Python is there or not.

If the system image (e.g. Debian box in Vagrant or base image in Google cloud) contains Python by default (whichever version), then you can assume that it's always there. If it does not, add a block a the beginning of the playbook that installs it with `raw`.
