### ISSUE TITLE
Concent VM: Connect to an external Geth node instead of setting up one inside the machine

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#268]
Geth requires a lot of space and is a common point of failure for us. I think that switching to an external node will make things easier for people using the virtual machine (#147).

- Remove geth from the machine.
- Remove extra disk images created to store the blockchain.
- Configure Golem and Concent to use an external node.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/162204094
