### ISSUE TITLE
Allow switching between an internal and external geth instance

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#285]
Currently every cluster runs Geth. Geth is pretty heavy when it comes to resources and it would be better to have just one, well maintained instance than many.

Add a variable called `external_geth_address`. It should either contain the public address of a Geth instance or be empty. If it's not empty, geth containers should not be deployed to the cluster at all. If it's empty an internal geth instance should be deployed and used.

**Comment by PaweuB** [comment]
Pivotal: https://www.pivotaltracker.com/story/show/163085505
