### ISSUE TITLE
Allow enabling routing based on golem-messages version even with a single cluster

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#289]
Our nginx-proxy can be configured to route HTTP messages based on golem-messages version included in the `X-Golem-Messages` (#258).

Currently there are only two possibilities: either there are exactly two GM versions available or the feature is completely disabled. The problem is that disabling it changes behavior of Concent endpoints because it disables all the checks against the header. When it's enabled, messages with GM version that's not available result in a HTTP 404. That's not the case when it's disabled. This makes the behavior inconsistent.

To alleviate this, we need to allow enabling routing even when there's only one cluster with one GM version available.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163020026
