### ISSUE TITLE
Optimize docker images to reduce build times

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#291]
Currently it takes 15 minutes to rebuild our containers in CI even with with Docker's caching. It's likely that we can reorder layers in the images to make caching more effective.

Having properly working cache would also help in cases where a rebuild is not necessary without having to check if the image already exists. If you run `concent-builder/build-test-and-push.yml` again on the same version, the build should be instant.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163085429

**Comment by bartoszbetka** [comment]
The docker layers that contains scripts that make installation of python packages with pip and `--no-cache-dir` flag cause slow build time. We should consider delete the `--no-cache-dir` flag from pip command and try to keep it cache outside docker image to don't increase it size.

**Comment by bartoszbetka** [comment]
I investigated this problem deeper and discovered that the main problem is the `__pycache__` directories and `.pyc` files. The second problem was the running ./manage.py collectstatic command in the `build/repositories/concent` path, not in the 'build/concent-api-assets` path. The building times now takes 2,3 minutes after second build with the same version was made.

When the versions are different, the problem still exists. I think the file `RELEASE-VERSION` causes this or something in` middleman_protocol`. I must investigate this case.

We should thinking about create docker images with installed dependencies and add it by `--cache-from` flag to the docker.
More info:
https://cloud.google.com/cloud-build/docs/speeding-up-builds

**Comment by cameel** [comment]
1) `--no-cache-dir` - let's start caching packages on the host. I've created #301.
2) `__pycache__` - we need to either remove these files or make sure they're not in Docker's context. You could also use [.dockerignore file](https://docs.docker.com/engine/reference/builder/#dockerignore-file) to make Docker ignore them.
3) `manage.py` - yeah, please fix this.
4) `middleman_protocol` - if it's what you told me (`requirements.lock` includes `middleman_protocol` which means that requirements need to be reinstalled each time Concent's code changes) then I need to think about it. We'll likely change it but I'm not yet sure how exactly.
5) `--cache-from` I'd prefer not to do that because we would have to manually rebuild the base image with dependencies. I'd prefer it to be automatic so that we don't have to think about it and there are less opportunities to break something this way.

**Comment by bartoszbetka** [comment]
1. This step is not necessary any more, after repair 2 and 3 steps. The python packages are caches on docker layer level.
4. I think we should install `middleman_protocol` and `golem_message` in separate steps. They are change more often. The first step can help now as workaround.
5. I thinking about docker with system dependencies. The manually rebuild the base image is advantage to me because we can repair some incompatible library in separate environment. This behavior prevent unexpected error when building docker images.

**Comment by cameel** [comment]
> 1. This step is not necessary any more, after repair 2 and 3 steps. The python packages are caches on docker layer level.

No, it's still useful. If only one package changes we don't have to redownload the rest. But I agree that it makes adding the cache support less urgent. Just dealing with 2. and 3. will solve the problem in most situations for us.

> 4. I think we should install middleman_protocol and golem_message in separate steps. They are change more often. The first step can help now as workaround.

I'm thinking that too. You can start implementing it that way. But if we do this, I'll want to change `requirements.txt` too. So you may need to tweak it later.

> 5. I thinking about docker with system dependencies. The manually rebuild the base image is advantage to me because we can repair some incompatible library in separate environment. This behavior prevent unexpected error when building docker images.

But we already have similar behavior - the layers with system dependencies do not get automatically rebuilt when Debian releases new packages. That's because we don't hard-code versions for most packages and just use the latest. Docker won't see that they changed and won't rerun the dependency unless you manually clear the package or bump a version of one of the few packages that do have it hard-coded in our `versions.yml`.

BTW, your comment referred to the wrong bullet points which was confusing. I edited it to fix it.

**Comment by cameel** [comment]
For the `signing-service`/`middleman_protocol` problem, let's do this:
- In the `Makefile` generate a modified requirements file:
    - Let's call it `cacheable-requirements.lock`
    - Use `concent_api/requirements.lock` as a base
    - Remove the line `--editable ../middleman_protocol`
    - Add dependencies listed in `middleman_protocol/setup.py`
        - To get the list of dependencies run `middleman_proticol/setup.py egg_info`. This will generate a directory called `Middleman_Protocol.egg-info/`. `requires.txt` in that directory has the dependencies.
- In the `Dockerfile`:
    - Copy `cacheable-requirements.lock` to the image
    - Install the requirements
    - Copy the package containing `middleman_protocol/` and `concent_api/` to the image.

You can do it similarly with the signing service image.

This should be good enough for now. If we decide to remove `middleman_protocol` from the requirements in `concent` repo, I'll create a separate issue to update this code.

The `RELEASE-VERSION` files should not be a problem. Yeah, they break caching of the step that copies the sources to the image but that step is fast and is not followed by any heavy step.
