### ISSUE TITLE
Update verifier to golemfactory/blender 1.5

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#295]
Golem has released a new version of the Blender image (1.5) on DockerHub. This image is the base for our verifier and we should match the version used by the client.

This change should to go master only when Golem decides to use this new image in a new release.

Also make sure that older Concent versions (in a configuration with multiple clusters running different golem-messages versions) still use the old image.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163113592

**Comment by bartoszbetka** [comment]
This change is no longer needed. We now use the `golemfactory/blender_verifier` as base image (https://github.com/golemfactory/concent-deployment/pull/361).
