### ISSUE TITLE
Shared geth node outside of the clusters

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#305]
Currently we're running geth on every cluster. This, especially in case of a mainnet node, requires a lot of resources (lots of disk space, SSD, extra CPU and memory). The other services we're running in the clusters are all light and mostly stateless while geth needs special attention because. Its initialization is not instant and its state is very large. Given that we're starting to need ever more clusters (dev, ci, staging, testnet, mainnet, audit) and some of them may run in multiple versions, I think it makes sense to treat geth as a separate service. We should put it on a separate machine and share it between all the clusters.

1) Provision two new machines: `geth-testnet` (for a testnet instance of geth) and `geth-mainnet` (for a mainnet instance).
    - Put necessary `gcloud` commands in a script and commit it to the repository (in the `cloud/` directory)
        - Create a new instance in Google Compute Engine
        - Attach disks (SSD for the mainnet node)
        - Reserve a static external IP
2) Put configuration variables in `geth-testnet.yml` and `geth-mainnet.yml` in concent-deployment-values repository.
3) Create a `geth/configure.yml` playbook in the repository. It should accept `geth_instance` as a parameter (with `geth-testnet` and `geth-mainnet` as the only valid values).
    - Install dependencies, including Docker
    - Create a user that will be running geth.
    - Run geth in a docker container
    - Configure firewall rules to expose only the ports we really need to expose
    - Install nginx and route all the HTTP traffic through it. Only paths actually used by Concent should be available.
4) Make sure that it's not possible to change node configuration remotely. It should allow only obtaining information about the blockchain and submitting new transactions.

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163254190

**Comment by bartoszbetka** [comment]
Some information:
- Created a user for running geth in docker gives nothing, because geth docker image uses root user, so procces works as root user.
- We decided to put connection parameters for geth instances in `ansible_inventory` file. The solution is not perfect because there are the case that ip parameter is change.

**Comment by cameel** [comment]
> Created a user for running geth in docker gives nothing, because geth docker image uses root user, so procces works as root user.

OK. Maybe it would actually be better not to run it in Docker. But let's leave it at that for now. We may always change it later.
