### ISSUE TITLE
Python 3.6 on the cluster

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#31]
Currently we're using Debian Stretch which offers only Python 3.5. We want to use 3.6. Best if we don't have to build it from source during deployment.

**Comment by cameel** [comment]
golem-messages (since 1.10) and Golem have switched to Python 3.6 as the minimum requirement. We should too. We should update as soon as possible.

@bartoszbetka Please do this as the first task on Monday.

**Comment by bartoszbetka** [comment]
> Currently, there are two common tools for creating Python virtual environments:
>- venv is available by default in Python 3.3 and later, and installs pip and setuptools into created virtual environments in Python 3.4 and later.
>- virtualenv needs to be installed separately, but supports Python 2.6+ and Python 3.3+, and pip, setuptools and wheel are always installed into created virtual environments by default (regardless of Python version).

https://packaging.python.org/tutorials/installing-packages/
