### ISSUE TITLE
SCI Callback to Middleman connection retry(setting)

### ISSUE THREAD

**Issue by Jakub89** [golemfactory/concent-deployment#311]
Followup to [#850](https://github.com/golemfactory/concent/issues/850)
We add new setting: `SCI_CALLBACK_RETRIES_TIME = 60` (can be the same value for all clusters).
It's absolutely have to be always bigger then `SCI_CALLBACK_MAXIMUM_TIMEOUT`, which is not a setting, but constant in `concent_api/core/constants.py`. I've made `system_check` for it, but I don't know if it apply to deployment. So if it possible to validate, it should be done also.

**Comment by PaweuB** [comment]
This issue is not valid any more

**Comment by cameel** [comment]
Could you explain in more detail why it's not valid? As far as I know we do need this setting. Please don't close issues without a proper explanation.

**Comment by Jakub89** [comment]
@cameel I didn't understood how adding settings works from deployment perspective. Most settings are empty in concent `base.py`, that's why we need deployment issue as well. In this case `SCI_CALLBACK_RETRIES_TIME` can be universal for all environments, so I add it to be equal to `60` in concent `base.py` settings. That's why @bartoszbetka don't need to add it separately.

**Comment by cameel** [comment]
OK. Great.
