### ISSUE TITLE
Python 3.6  has been removed from debian testing repository

### ISSUE THREAD

**Issue by bartoszbetka** [golemfactory/concent-deployment#321]
Python `3.6` package  has been removed from debian `testing` repository and currently it's can be find only in `unstable` repository. We must find some solution to this problem.

According information:
https://tracker.debian.org/news/1025205/python36-removed-from-testing/
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=python3.6

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163552043
