### ISSUE TITLE
Concent VM: Move hyperg version to versions.yml

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#333]
Version and hash of `hyperg` for Concent VM is now in `concent-vm/consts.yml`. Move them to `containers/versions.yml`.

This was reported in https://github.com/golemfactory/concent-deployment/pull/324/files#r253417412 but was not a part of that pull request.

**Comment by PaweuB** [comment]
Pivotal: 
https://www.pivotaltracker.com/story/show/163861243
