### ISSUE TITLE
Do not include user and group name in tarballs

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#334]
When we're building tarballs with Signing Service or intermediate ones during build the archive contains user and group name for each file, which is unnecessary and makes the file different even if the files themselves are the same. Always use `--owner=0 --group=0 --numeric-owner` options when running `tar`.

See also [Debian > ReproducibleBuilds > UsersAndGroupsInTarballs](https://wiki.debian.org/ReproducibleBuilds/UsersAndGroupsInTarballs)

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163861190
