### ISSUE TITLE
Automate generating keys for Signing Service

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#335]
Currently we only have manual instructions for generating keys for the Signing Service. These are keys used by golem-messages and their format is publicly known. We could make it simpler though.

1) Create a Python script (`generate-ecc-key-pair.sh`) that:
    - Generates an ECC key pair
    - Encodes the keys in the format that can be passed to Signing Service
    - Prints the keys to the screen
2) Put the script in `/usr/local/bin` in the `signing-service` container
3) Add a Docker command for running the script to the README and explain when it should be used

**Comment by PaweuB** [comment]
Pivotal:
https://www.pivotaltracker.com/story/show/163824173
