### ISSUE TITLE
Make Django error mailer send e-mails to the newly created mail group rather than every person individually

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#35]
Update the value for `ADMINS` setting in `concent-deployment-values` so that it contains only the address of the mailing group rather than individual e-mail addresses. This will make it harder to exceed the daily e-mail quota on sendgrid.

Test that it works by causing error 500 on the `concent-dev` cluster.

**Comment by Gr33ny** [comment]
https://github.com/golemfactory/concent-deployment-values/pull/3

**Comment by cameel** [comment]
Done in golemfactory/concent-deployment-values#3 and merged into master: https://github.com/golemfactory/concent-deployment-values/commit/da22168f2acc7c0f27e41b4f89903726ac5cd8e0
