### ISSUE TITLE
Separate deployment server

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#369]
Our build server should not have access to the mainnet clusters or mainnet credentials. Too many people have access to it and there are too many things that are happening there - it builds Docker images (which basically gives anyone who can do it an easy way to gain root privileges) and serves Jenkins UI. For that reason we need a separate machine that's just for deploying to mainnet and managing infrastructure with `gcloud`.

1. Provision a new machine called `concent-deployment-server`.
    - Give it a minimal amount of CPU and RAM.
    - Give it a static IP.
    - Automate the process with a playbook or a shell script. Put it under `cloud/` in the repository.
2. Create user accounts on the new machine either manually or by adding keys to instance metadata (see [Managing SSH Keys in Metadata](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys))
3. Create a playbook for configuring the machine. It should be similar to the one used for `concent-builder` but without the unnecessary stuff:
    - Without Jenkins or nginx
    - Without Docker
4. Make it possible to run some of the playbooks from `concent-builder` on this machine too:
   - `install-secrets.yml`
       - The deployment server should use a separate service account. If it has not been created yet, it's fine to temporarily use the one from `concent-builder`.
   - `install-repositories.yml`
       - Cloning the `concent` repository is not necessary on the deployment server but it's fine to leave it in the playbook for the sake of keeping it simple.
   - `deploy.yml`
   - `migrate-db.yml` and `reset-db.yml`
   - `redeploy-nginx-proxy-router.yml`
   - `job-cleanup.yml`
5. It would be best to extract common parts of the playbooks into Ansible roles but that might be a significant refactoring. For now don't focus on it and just do it in any way that avoids duplicating the playbooks. E.g. by using includes.
6. Add information about configuring and using the new machine to the README.

**Comment by bartoszbetka** [comment]
The solution will be modified after discussion, we must add the ability of using the `staging` and` testnet` cluster environments.
