### ISSUE TITLE
Use OS Login instead of managing SSH keys manually

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#370]
Currently our GCP instances have a combination of SSH accounts authorized manually and via instance metadata. It would be better to switch to the OS Login method (see [Managing Instance Access Using OS Login](https://cloud.google.com/compute/docs/instances/managing-instance-access)). This would allow us to use IAM permissions to control who can use which machine and who has sudo access.

1. Enable OS Login.
    - Note that this may make some of the current accounts on `concent-builder` inaccessible. People need to reauthenticate using `gcloud`. If necessary, move their files to their new home directories afterwards.
2. Clean up user accounts
    - Remove sudo access for developers.
    - Remove accounts of people no longer working on the project.
3. Make sure roles are set correctly
    - Developers: `roles/compute.osLogin` role for `concent-builder` machine.
    - DevOps: `roles/compute.osAdminLogin` role for `concent-builder`, `concent-deployment-server` and the Geth machines.
4. Make sure that everyone can log into their account.
5. Add information on how to gain SSH access to README.

**Comment by bartoszbetka** [comment]
The OS Login feature works with users that belong to the organization that creates a project on google cloud. This feature not work in our case, because we belong to outside organization. However, there is possibility to use the `roles/compute.osLoginExternalUser` role at project and organization level. 
More info: https://cloud.google.com/compute/docs/instances/managing-instance-access#external_user

**Comment by cameel** [comment]
Well, that's an unexpected limitation. I thought that there can be more than one organization assigned to a project and that only the people without any organization are treated as external users.

In that case let's keep using SSH keys as we do now - with only a slight change. Right now you're manually creating accounts as needed and putting public keys in `~/.ssh/authorized_keys`. There's a way to avoid doing this. Please put our keys into [project-wide SSH keys](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys#project-wide). But only our current keys. In the future, let's prefer the keys generated by `gcloud compute ssh` instead of adding people's own keys to metadata. At least for anyone who can generate them.

According to [How to provide access to only one instance to users in Google Compute Engine?](https://serverfault.com/questions/898507/how-to-provide-access-to-only-one-instance-to-users-in-google-compute-engine) there are four privileges that are required to allow logging into machines this way:
1. `compute.projects.get`
2. `compute.zoneOperations.get`
3. `compute.instances.get`
4. `compute.instances.setMetadata`

These privileges are already included in the `Editor` role. That's why we can log into the machines using [SSH in the browser](https://cloud.google.com/compute/docs/ssh-in-browser). The key generated on the spot gets added to instance metadata.

`Viewer` role is missing the last one so I think viewers can't - but please verify that.

**Comment by bartoszbetka** [comment]
We decided to block ssh connection with all instances for developers. All `project-wide SSH keys` have been deleted. They are automatically create when use `gcloud compute ssh <instance_name>` command or by using google cloud console. 
Viewer role can't connect to instances.
