### ISSUE TITLE
Installing extra files from blender_verifier required to run integration tests

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#374]
In https://github.com/golemfactory/concent/issues/1127 we're adding an additional step required to set up Concent for development or running integration tests - downloading extra files that normally reside in `blender_verifier` image. You don't need this step for normal deployment but you probably do when running integration tests in Jenkins.

1. Add `golem_version` to `containers/versions.yml`.
2. Use that version as a parameter for the script that downloads the extra files before Jenkins runs the tests.
    - If we're starting the tests from within a Docker image, it's also fine to include these files in the image at build time.

**Comment by kbeker** [comment]
Also please add setting which will be pointing where extra files will be downloaded. Name of this setting could be  `BLENDER_RENDER_TOOLS_DIR`

**Comment by bartoszbetka** [comment]
We discussed the changes and they are not required. The current implementation process has been tested.
