### ISSUE TITLE
Switch all of our clusters to standalone geth

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#376]
Currently most of our clusters have their own Geth instances. In #285 we made it possible to for a cluster to use external Geth instance and in #305 we have created instances for testnet and mainnet. Now we can switch our clusters to those instances which should reduce resource usage and also make synchronization problems less frequent.

- Reconfigure all the `dev`, `ci`, `staging` and `testnet` clusters to use our new external geth nodes.
    - Do it for both GM versions.
- Remove the disks we currently have reserved for Geth on those clusters
- If possible, reduce the amount of CPU and memory allocated for those clusters (if not already done in #377).

**Comment by cameel** [comment]
@bartoszbetka Could you give me an update on the status of this task? What has been done and what remains to be done?

**Comment by bartoszbetka** [comment]
Steps that already done: `1, 2` for clusters: `dev, ci, staging`.

**Comment by bartoszbetka** [comment]
Step 3 is describe in #377.

**Comment by bartoszbetka** [comment]
Closed after updating the `testnet` clusters.
