### ISSUE TITLE
Fluentd DaemonSet

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#40]
Our logs in StackDriver are very messy and hard to analyze. For example entries starting with `INFO` are sometimes classfied as errors. To deal with it we need to be able to customize the parsing rules. This requires configuring fluentd. Unfortunately GKE does not let us configure its own logging agent so we have to deploy our own DaemonSet with fluentd.

Do the following:
- Create fluentd DaemonSet and ConfigMap in the `kube-system` namespace (see [container-engine-customize-fluentd/kubernetes/](https://github.com/GoogleCloudPlatform/container-engine-customize-fluentd/tree/master/kubernetes))
- Create fluentd config based on [fluentd-configmap.yaml from GoogleCloudPlatform/container-engine-customize-fluentd repository](https://github.com/GoogleCloudPlatform/container-engine-customize-fluentd/blob/master/kubernetes/fluentd-configmap.yaml)
    - See if we really need all this boilerplate. I hope that we don't need to define and maintain rules for the Kubernetes stuff. It's best if we can focus only on the output of our own containers. If it's necessary, try to extract it into a separate file.
- Modify the configuration so that lines starting with `INFO ` always get serverity of `INFO`. Same for other [severity levels](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity).
- Deploy to `concent-dev` cluster and make sure that logs properly appear in the StackDriver panel.

If if makes things easier, you can start by setting up the [Stackdriver Logging Agent](https://cloud.google.com/logging/docs/agent/) instead of pure fluentd. This is simply fluentd with some default configs for GKE.

See:
- [container-engine-customize-fluentd](https://github.com/GoogleCloudPlatform/container-engine-customize-fluentd) repository with example configuration for a full cluster.
- [Customizing Stackdriver Logs for Kubernetes Engine with Fluentd](https://cloud.google.com/solutions/customizing-stackdriver-logs-fluentd)
- [fluentd v0.12 Quickstart Guide](https://docs.fluentd.org/v0.12/articles/quickstart)
- [GoogleCloudPlatform/fluentd-catch-all-config](https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/) - fluentd config files for a lot of typical cloud software.

**Comment by Gr33ny** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver/

**Comment by Gr33ny** [comment]
```If you’re using GKE and Stackdriver Logging is enabled in your cluster, you cannot change its configuration, because it’s managed and supported by GKE. ```
So we don't have to change our default **Deamonset**. 
Also we don't have to disable this configuration, because our logs will be in use by **Stackdriver**. 

We must a change default **ConfigMap** configuration: 
```Fluentd configuration is stored in the ConfigMap``` to make beauty our logs. 

To change it first we must write fluentd log parser to change logs to our necessity. 
Then we should change **ConfigMap** using a command from above [Kubernetes docs](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver/).

**Comment by bartoszbetka** [comment]
Branch with actual state: https://github.com/golemfactory/concent-deployment/commit/e7817f8c5e4dd4a36b0c75be912a9c2edf8cf6f2

**Comment by cameel** [comment]
I'm closing this since it has been replaced with #224.

Basically, we'll do the same thing but with Helm.
