### ISSUE TITLE
Deployment and service for RabbitMQ on the storage cluster

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#88]
- Create a deployment that uses the official [rabbitmq docker image](https://hub.docker.com/_/rabbitmq/)
    - Configure it to run one instance
- Provision a small persistent disk for the pod so that it can store its database in it (check how much storage it usually needs). Mount it as a volume in the right directory.
- Create a service that makes the pod available to other services on the storage cluster.

**Comment by bartoszbetka** [comment]
Some information:
- RabbitMQ delete message from queue after consumer send message acknowledgment.
According to: http://docs.celeryproject.org/en/latest/userguide/tasks.html#Task.acks_late Celery by default send ack before execute task.
-  The default memory threshold is set to 40% of available RAM (NOTICE: In worst case it can use 80% RAM). When RabbitMQ attained memory threshold, it raise memory alarm and block all connections that are publishing messages
- The default disk space threshold is set to 50MB. When disk space left drop below this limit,an alarm will be raised and all producers will be blocked.
- Lazy Queues feature which move queues content to disk space and load them in RAM when requested by consumer More Info: https://www.rabbitmq.com/lazy-queues.html
- Enable HiPE:
> Set to true to precompile parts of RabbitMQ with HiPE, a just-in-time compiler for Erlang. This will increase server throughput at the cost of increased startup time. You might see 20-50% better performance at the cost of a few minutes delay at startup.
- Posible to use TTL for message and queue
- Durable queues and messages are persisted to disk and thus survive broker restarts. Celery by default using durable queues and messages. According to: http://docs.celeryproject.org/en/latest/userguide/optimizing.html#using-transient-queues, http://docs.celeryproject.org/en/latest/userguide/configuration.html#task-default-delivery-mode, https://www.rabbitmq.com/queues.html

**Comment by bartoszbetka** [comment]
The default name of the `rabbitmq` node is the `hostname` whose name in kubernetes is the name of the nodes. This name is random and change after restarting, deleting, etc. This behavior causes creates a new database for the new node, so we can not recover messages and queues. We need a constant name of `rabbitmq` node, so we can read messages and queues from an existing database. 
Solution:
- Add a `hostname` field in the kubernetes deployment, which will change the host name of the pod. When we add more pods with `rabbitmq`, we'll have to manually change their host names. This solution is implemented.
- Add `RABBITMQ_NODENAME`  environment variable, which will change the name of the rabbitmq node. This solution causes a problem with restarting the rabbitmq pods.

Some information:
- https://www.rabbitmq.com/configure.html
