### ISSUE TITLE
Verifier: Kubernetes deployment

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#91]
Create a Kubernetes deployment and service for the `verifier` app (https://github.com/golemfactory/concent/issues/220) using the `verifier` image (#90) for the implementation of https://github.com/golemfactory/concent/issues/193 blueprint.

- Define Kubernetes deployment
    - Define resource limits for the image.
        - Find out how much memory and CPU we need to run the `verifier` app, Blender, file uploads/downloads, image comparison.
        - Keep in mind that `verifier` app and Blender will both be running at the same time.
        - It's enough to get just rough estimates. We'll need to determine real limits buy observing how it behaves under load in integration tests.
    - Run two instances of verifier pod on the `dev` and `staging` clusters. Or three if our current resources allow it. Let me know if we need to add more CPU or memory.
- Define Kubernetes service
- Add `local_settings`. Compared to `local_settings` for `concent-api` There should be the following differences:
    - Not connected to the database
    - `ALLOWED_HOSTS` can be empty (it won't be running a web server).
    - `CONCENT_FEATURES`: set to `['verifier']`.
    - `STORAGE_SERVER_INTERNAL_ADDRESS`: set to the internal address of nginx-storage (`http://nginx-storage/`; HTTPS if it's configured not to allow HTTP).
    - `VERIFIER_STORAGE_PATH`: path to a directory where verifier can store its files. It should be the directory where the persistent disk will be attached (#93).

**Comment by cameel** [comment]
@bartoszbetka Is this done?

**Comment by bartoszbetka** [comment]
Yes, it's done.
