### ISSUE TITLE
Verifier storage

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#93]
This is a part of the implementation of https://github.com/golemfactory/concent/issues/193 blueprint.

We need persistent disks for `verifier` pods implemented in #91.

- Provide a persistent disk for each `verifier` pod. Each disk should have 20 GB of space. Call them `verifier-storage-<cluster>-<N>` where `<cluster>` is the cluster name and `<N>` is a number, starting with 1.
- Create ansible playbooks for automatically creating and deleting persistent disks for `verifier`.

**Comment by cameel** [comment]
@bartoszbetka Is this done?

**Comment by bartoszbetka** [comment]
Yes, it's done
