### ISSUE TITLE
nginx configuration for file uploads in development

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#94]
We need a simple way to run nginx with file uploads in development so that we can work on verifier without connecting to a real cluster.

Create a simple script that starts nginx in a container on a local machine with configuration that allows the client to upload arbitrary files to a predefined directory. Upload URLs and headers should work the same way as in `nginx-store` except for gatekeeper. We don't need gatekeeper for this.

See my script that does this for downloads: https://github.com/golemfactory/concent/issues/221#issuecomment-376557367. You can extend it to support uploads too. Maybe make the port configurable (so that it can be passed from command line). Post the result in a comment in this issue. Or commit it to the Concent repository.

Use the upload method that's easiest to configure. It does not need to be `nginx-big-upload` because we don't need all its features in this use case.

**Comment by cameel** [comment]
BTW, here's my old script that simulates gatekeeper: https://github.com/golemfactory/concent-deployment/issues/19#issuecomment-349301097

I don't think you'll need it here but I'm linking it just in case.

**Comment by bartoszbetka** [comment]
### Running a local `nginx` container for upload and download files

Save this in a file called `run-nginx-storage.sh`:
```
#!/bin/bash -e

DEFAULT_PORT=80

port="${1:-$DEFAULT_PORT}"

mkdir --parents /tmp/nginx-storage/{download,config}/

nginx_root=/tmp/nginx-storage

cat <<- EOF > $nginx_root/config/nginx-storage.conf
server {
    listen  127.0.0.1:$port;
    charset utf-8;

    location / {
        root    $nginx_root/download;
        index   index.html index.htm;
    }

    location /download/ {
        alias $nginx_root/download/;
    }

    location /upload/ {

        if (\$http_concent_upload_path = "") {
           return 400 '{"error_message": "Concent-Upload-Path header is missing.", "error_code": "missing-header"}\n';
        }

        if (\$http_content_length = 0) {
           return 400 '{"error_message": "The file to be uploaded must not be empty.", "error_code": "empty-file"}\n';
        }

        limit_except POST              { deny all; }
        client_body_temp_path          $nginx_root/download/;
        client_body_in_file_only       on;
        client_body_buffer_size        128K;
        client_max_body_size           300M;
        proxy_pass                     http://127.0.0.1:$port/upload-internal/;
    }

    location /upload-internal/ {
        return 200 '{"message": "File was successfully uploaded"}';
    }

}
EOF

cat <<- EOF > $nginx_root/download/index.html
<html>
    <body>
        <h1>nginx-storage</h1>
        <p>All files located in $nginx_root/download/ can now be downloaded from URLs starting with http://localhost/download/.</p>
        <p>All uploaded files can be found in the $nginx_root/download/ directory.
        To upload a file, you must use the POST method and add the Concent-Upload-Path header to the http://localhost/upload/ url.</p>
        <p>Example upload: ' curl -X POST http://localhost/upload/ --data-binary "@result" -H "Concent-Upload-Path: blender/task/result" '</p>
    <body>
<html>
EOF

sudo systemctl start docker

docker run                                                                           \
    --rm                                                                             \
    --volume $nginx_root/config/nginx-storage.conf:/etc/nginx/conf.d/default.conf:ro \
    --volume $nginx_root/download/:$nginx_root/download/:rw                          \
    --net    host                                                                    \
    --name   nginx-storage                                                           \
    nginx:alpine
```

Make it executable:
``` bash
chmod +x run-nginx-storage.sh
```

The script starts docker (if it's not running yet), downloads a nginx image and configures it. 
The uploaded file can be found in `/tmp/nginx-storage/download`. The file name is random, but the contents of the files are not change. More info is available in `http://localhost/`

If you already have a server running at port 80, you can change default port(80) for example to 100:
```
./run-nginx-storage.sh "100"
```

**Comment by cameel** [comment]
The script is in the comment above and the task is done. I'm closing it.
