### ISSUE TITLE
Make Sentry reports from different clusters easier to discern

### ISSUE THREAD

**Issue by cameel** [golemfactory/concent-deployment#97]
Currently e-mails from sentry do not contain anything that would let us discern whether the error comes from `concent-dev` or `concent-staging`.

One idea is to put `dev` or `staging` in the `release` field in `settings.RAVEN_CONFIG`. See how much it changes the e-mails.

See what else we could change to make it more apparent.

**Comment by cameel** [comment]
I changed the title in `Project Settings > Alerts` according to your suggestion ([Can I change the subject line for alert emails?](https://help.sentry.io/hc/en-us/articles/115001651153-Can-I-change-the-subject-line-for-alert-emails-)).

Now it's: `[$project/${tag:release}] ${tag:level}: $title`

I have also discovered that we can set `environment` in `settings.RAVEN_CONFIG`. Please use it instead of `release`.

Here are all fields we can use in `RAVEN_CONFIG`: [Sentry > SDKs > Python > Advanced Usage > Client Arguments](https://docs.sentry.io/clients/python/advanced/#client-arguments).

**Comment by cameel** [comment]
Changed the title to `[$project/${tag:environment}] ${tag:level}: $title`

**Comment by cameel** [comment]
Changed title to `[${tag:environment}] ${tag:level}: $title`.
And `Subject Prefix` in `General` to `[Sentry]` (without a space at the end).

Now the title should look like this:
```
[Sentry][concent-staging] error: OperationalError: FATAL: password authentication failed for user "concent_staging_user"
```

**Comment by bartoszbetka** [comment]
Tag was changed from `release` to `environment`.

**Comment by cameel** [comment]
More changes (from a conversation we had just now):
- Add a tag with the container name (`concent-api`, `gatekeeper`, etc.)
- I'll include the tag in the title.

**Comment by cameel** [comment]
Title changed to `[${tag:environment}/${tag:component}: $title`. Now it should look like this:

`[Sentry][concent-staging/gatekeeper] error: OperationalError: FATAL: password authentication failed for user "concent_staging_user"`
